AWSTemplateFormatVersion: 2010-09-09
Description: Selenium / Chromium Lambda function sample
    
Parameters:
    BucketName:
        Description: S3 Bucket
        Type: String    

    WebSite:
        Description: Take screenshot of this URL 
        Type: String  
        Default: "https://parents.genesisedu.com/ftlee/parents?tab1=studentdata&tab2=studentsummary&studentid=29060860&action=form"

    SourceFolder:
        Description: folder in S3 Bucket where source files are located (lambda)
        Type: String
        Default: "src"

    ScreenshotsFolder:
        Description: folder in S3 Bucket where store screenshots
        Type: String
        Default: "screenshots"
        
    Email:
        Description: email to login
        Type: String

    Pwd:
        Description: pwd to login
        Type: String
    
    TopicArn:
        Description: The SNS topic to send the notification with result
        Type: String

Resources:

    ScreenshotFunctionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                -   Effect: Allow
                    Principal:
                        Service:
                        - lambda.amazonaws.com
                    Action:
                    - sts:AssumeRole
            Policies:
                -   PolicyName: Allow-logs
                    PolicyDocument:
                        Version: '2012-10-17'
                        Statement:
                        -   Effect: Allow
                            Action:
                            - 'logs:CreateLogGroup'
                            - 'logs:CreateLogStream'
                            - 'logs:PutLogEvents'
                            Resource: arn:aws:logs:*:*:*   
                -   PolicyName: BucketGetPutObject
                    PolicyDocument:
                        Version: '2012-10-17'
                        Statement:
                        -   Effect: Allow
                            Action:
                            - 's3:GetObject'
                            - 's3:PutObject'
                            Resource: 
                                Fn::Join: ["", ["arn:aws:s3:::", Ref: "BucketName", "/*"]] 
                -   PolicyName: Allow-sns
                    PolicyDocument:
                        Version: '2012-10-17'
                        Statement:
                        -   Effect: Allow
                            Action:
                            - 'SNS:Publish'
                            Resource: arn:aws:sns:*:*:*
                

    ScreenshotFunction:
        Type: AWS::Lambda::Function
        Properties:
            Runtime: python3.7
            Description: Function to take a screenshot of a website.
            Handler: src/lambda_function.lambda_handler
            Role: 
                Fn::GetAtt: [ "ScreenshotFunctionRole", "Arn" ]
            Environment:
                Variables:
                    PYTHONPATH: "/var/task/src:/opt/python"
                    PATH: "/opt/bin:/opt/bin/lib"
                    URL: 
                        Ref: WebSite
                    BUCKET:
                        Ref: BucketName
                    DESTPATH:
                        Ref: ScreenshotsFolder
                    Email:
                        Ref: Email
                    Pwd:
                        Ref: Pwd
                    TopicArn:
                        Ref: TopicArn
            Timeout: 60
            MemorySize: 2048
            Code:
                S3Bucket: 
                    Ref: BucketName
                S3Key: 
                    Fn::Sub: '${SourceFolder}/ScreenshotFunction.zip'
            Layers:
                - Ref: SeleniumChromiumLayer

    SeleniumChromiumLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            CompatibleRuntimes:
                - python3.7
                - python3.6
            Content:
                S3Bucket: 
                    Ref: BucketName
                S3Key: 
                    Fn::Sub: '${SourceFolder}/SeleniumChromiumLayer.zip'
            Description: Selenium and Chromium Layer for Python3.6
